services:
  app:
    build: .
    container_name: yunexpress-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - ./logs:/app/logs
    # depends_on:
    #   - mysql
    networks:
      - app-network
    command: ["node", "server.js"]

  worker:
    build: .
    container_name: yunexpress-worker
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./logs:/app/logs
      - /dev/shm:/dev/shm
    # depends_on:
    #   - mysql
    networks:
      - app-network
    shm_size: '2gb'
    security_opt:
      - seccomp:unconfined
    command: ["node", "worker.js"]

  # mysql:
  #   image: mysql:8.0
  #   container_name: yunexpress-mysql
  #   restart: unless-stopped
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_DATABASE: ${DB_NAME}
  #     MYSQL_USER: ${DB_USER}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #     TZ: ${TZ}
  #   volumes:
  #     - mysql-data:/var/lib/mysql
  #   networks:
  #     - app-network

networks:
  app-network:

# volumes:
#   mysql-data: